export const AUTH = {
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_LOADING:"SIGNUP_LOADING",
    SIGNUP_ERROR:"SIGNUP_ERROR",
    
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_LOADING:"LOGIN_LOADING",
    LOGIN_ERROR:"LOGIN_ERROR",

    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_LOADING:"LOGOUT_LOADING",
    LOGOUT_ERROR:"LOGOUT_ERROR",

    GET_SUCCESS:"GET_SUCCESS",
    GET_LOADING:"GET_LOADING",
    GET_ERROR:"GET_ERROR",

    RESET:"RESET"
}